### ISSUE TITLE
better performance

### ISSUE THREAD

**Issue by bachig26** [Layendan/NineAnimator-Tauri#27]
as you might know that I have been using your app at times to keep tabs on the progress since Nov/Dec 2022, the latest version is actually better than ever.

But it still feels laggy and stuttering. i would like to see it get more smoother and possibly resource hungry which I feel like the app consumes too much ram/memory while running. it's acceptable while at ideal.
for example, (during a checkup) at ideal state, it consumes around 4MB and while searching and streaming, etc it consumes around ~250MB to ~500MB.

**Comment by Layendan** [comment]
Thanks for your feedback and use of it!
Since this is what I use to watch anime, I try and make it so that it feels nice to use for myself, but it's hard to know if it's good for others or not.

Yeah app performance is one thing that I really need to work on. Especially downloading episodes when you're browsing an anime with more that like 20-50 episodes since that eats up the CPU.
I've never really noticed the app eating up the RAM. I'll try to look into it and try and figure out why that's happening.
Current theory is that it's creating multiple WebWorkers which might be causing the issue, but I'll try and figure that out.

edit: Another thing that I want to remove is the FFMPEG executable packaged with the app, since that takes up about 90-100+ mb of storage when the app is less than 10mb (if not less, can't remember actual size of app). Which should make the app a lot more lightweight (although it won't affect performance)

**Comment by Layendan** [comment]
> the app consumes too much ram/memory while running. it's acceptable while at ideal. for example, (during a checkup) at 
> ideal state, it consumes around 4MB and while searching and streaming, etc it consumes around ~250MB to ~500MB.

So I looked a bit into it, and I think the reason why it is using so much memory is because of the cache and the stores are storing an ungodly amount of information. I should be able to reduce the amount of memory taken, but I'm not planning it that low since it is still very useful/needed to have that information stored (eg. caching responses so that navigating backwards and clicking on an anime that you already navigated to doesn't require for you to wait. and downloaded anime data/subscriptions/recently watched).

For more info, what pages does it consume the least/most for your computer while running the app? What is happening (downloading anime, watching anime, idling on a certain page...)?


> But it still feels laggy and stuttering. i would like to see it get more smoother

I'm not too sure why it is doing that, since I also get it on both of my beefy computers. It might be because of the skeleton animations of certain components which might be eating up the cpu for rendering which in turn makes the app super slow. Might replace with a jump animation. And I know the parrallax scroll on both the main page, and the anime info page lag computers, which is why I made a setting to turn it off since it would lag my laptop. Another thing that lags a lot is the "check for updates" button on subscriptions. But atm I'm not planning on fixing that. Another thing is navigating which requires the app to remove some of the components and re-adding them which might be cpu intensive in certain contexts.

What are you doing/what is happening in the app when it lags and starts stuttering?

**Comment by Layendan** [comment]
The ram usage should be fixed in the new update.

I still haven't had any problems with studders apart from fetching new updates for subscriptions and staying on the anime info page while downloading a lot of episodes at the same time. If you can, please send me more information on the stuttering such as when it happens, what page it happens in, and what's happening at that moment.
