### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by freitassdev** [Layendan/NineAnimator-Tauri#29]
Hello! I want to start an anime streaming project, could you tell me which api/provider you used to get the anime videos?

**Comment by Layendan** [comment]
I use consumet for grabbing the information and video links.

Basically it just grabs anilist info and combines it with website video links.
Here's the API github link: https://github.com/consumet/api.consumet.org
I use this for the app, which I self host on azure.

There's also a JS/TS library for it if you want to use this instead
https://github.com/consumet/consumet.ts

I know that they have a discord and documentation for settings things up.

Sadly since enime got shut down, episode images, names, and I think descriptions got removed so it won't have the full information anymore.
